In [ ]:
df_grouped = df.groupby('Department')

df_grouped.get_group('Technical')

     Name Department     Employment Type  Salary  Years of Experience
2  Sourav  Technical              Intern   70000                    2
3    Riya  Technical  Part-time Employee   70000                    3
6   Rohan  Technical  Full-time Employee  125000                    6
8  Soumya  Technical              Intern   50000                    1

In [ ]:
import pandas as pd

# Create the data of the DataFrame as a dictionary
data_df = {'Name': ['Asha', 'Harsh', 'Sourav', 'Riya', 'Hritik',
                    'Shivansh', 'Rohan', 'Akash', 'Soumya', 'Kartik'],

           'Department': ['Administration', 'Marketing', 'Technical', 'Technical', 'Marketing',
                          'Administration', 'Technical', 'Marketing', 'Technical', 'Administration'],

           'Employment Type': ['Full-time Employee', 'Intern', 'Intern', 'Part-time Employee', 'Part-time Employee',
                               'Full-time Employee', 'Full-time Employee', 'Intern', 'Intern', 'Full-time Employee'],

           'Salary': [120000, 50000, 70000, 70000, 55000,
                      120000, 125000, 60000, 50000, 120000],

           'Years of Experience': [5, 1, 2, 3, 4,
                                   7, 6, 2, 1, 6]}

# Create the DataFrame
df = pd.DataFrame(data_df)
df

       Name      Department     Employment Type  Salary  Years of Experience
0      Asha  Administration  Full-time Employee  120000                    5
1     Harsh       Marketing              Intern   50000                    1
2    Sourav       Technical              Intern   70000                    2
3      Riya       Technical  Part-time Employee   70000                    3
4    Hritik       Marketing  Part-time Employee   55000                    4
5  Shivansh  Administration  Full-time Employee  120000                    7
6     Rohan       Technical  Full-time Employee  125000                    6
7     Akash       Marketing              Intern   60000                    2
8    Soumya       Technical              Intern   50000                    1
9    Kartik  Administration  Full-time Employee  120000                    6

In [ ]:
# Group by department and find average salary of each group
df.groupby('Department')['Salary'].mean()

Department
Administration    120000.0
Marketing          55000.0
Technical          78750.0
Name: Salary, dtype: float64

In [ ]:
groups = df.groupby(by='Department')
groups.groups

{'Administration': [0, 5, 9], 'Marketing': [1, 4, 7], 'Technical': [2, 3, 6, 8]}

In [ ]:
groups = df.groupby(by=['Department', 'Employment Type'])
groups.groups

{('Administration', 'Full-time Employee'): [0, 5, 9], ('Marketing', 'Intern'): [1, 7], ('Marketing', 'Part-time Employee'): [4], ('Technical', 'Full-time Employee'): [6], ('Technical', 'Intern'): [2, 8], ('Technical', 'Part-time Employee'): [3]}

In [ ]:
# Separate the rows into groups that have the same department
groups = df.groupby(['Department'])

# View the sum of the numeric features of each group
groups.aggregate('sum')

<ipython-input-9-df0f0c4d3706>:5: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groups.aggregate('sum')

                Salary  Years of Experience
Department
Administration  360000                   18
Marketing       165000                    7
Technical       315000                   12

In [ ]:
# Separate the rows into groups that have the same department nad employment type
groups = df.groupby(['Employment Type', 'Department'])

# View the average of the numeric features of each group
groups.aggregate('mean')

<ipython-input-10-7381342f3e7f>:5: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groups.aggregate('mean')

                                     Salary  Years of Experience
Employment Type    Department
Full-time Employee Administration  120000.0                  6.0
                   Technical       125000.0                  6.0
Intern             Marketing        55000.0                  1.5
                   Technical        60000.0                  1.5
Part-time Employee Marketing        55000.0                  4.0
                   Technical        70000.0                  3.0

In [ ]:
# Separate the rows into groups that have the same department
groups = df.groupby('Department')

# View the sum and the average of the numeric features of each group
groups.aggregate(['mean', 'sum'])

<ipython-input-11-5963b7323d2d>:5: FutureWarning: ['Name', 'Employment Type'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  groups.aggregate(['mean', 'sum'])

                  Salary         Years of Experience
                    mean     sum                mean sum
Department
Administration  120000.0  360000            6.000000  18
Marketing        55000.0  165000            2.333333   7
Technical        78750.0  315000            3.000000  12

In [ ]:
# Separate the rows into groups that have the same department
groups = df.groupby('Department')

# View the first observation of each group
groups.first()

                  Name     Employment Type  Salary  Years of Experience
Department
Administration    Asha  Full-time Employee  120000                    5
Marketing        Harsh              Intern   50000                    1
Technical       Sourav              Intern   70000                    2

In [ ]:
# Separate the rows into groups that have the same department
groups = df.groupby('Department')

# View the statistical summary of the groups
groups.describe()

               Salary                                                        \
                count      mean           std       min       25%       50%
Department
Administration    3.0  120000.0      0.000000  120000.0  120000.0  120000.0
Marketing         3.0   55000.0   5000.000000   50000.0   52500.0   55000.0
Technical         4.0   78750.0  32242.570204   50000.0   65000.0   70000.0

                                   Years of Experience                      \
                     75%       max               count      mean       std
Department
Administration  120000.0  120000.0                 3.0  6.000000  1.000000
Marketing        57500.0   60000.0                 3.0  2.333333  1.527525
Technical        83750.0  125000.0                 4.0  3.000000  2.160247


                min   25%  50%   75%  max
Department
Administration  5.0  5.50  6.0  6.50  7.0
Marketing       1.0  1.50  2.0  3.00  4.0
Technical       1.0  1.75  2.5  3.75  6.0

In [ ]:
# Separate the rows into groups that have the same department
groups = df.groupby('Department')

# View the number of observations present in each group
groups.size()

Department
Administration    3
Marketing         3
Technical         4
dtype: int64

In [ ]:
# Separate the rows into groups that have the same department
groups = df.groupby('Department')

# View the number of unique observations in each feature of the groups
groups.nunique()

                Name  Employment Type  Salary  Years of Experience
Department
Administration     3                1       1                    3
Marketing          3                2       3                    3
Technical          4                3       3                    4

In [ ]:
# Separate the rows into groups that have the same department
groups = df.groupby('Department')

# Change the column name 'Salary' to 'Department Expenditure'
groups.aggregate('sum').rename(columns={'Salary': 'Department Expenditure'})

<ipython-input-16-c1877ebbd1f7>:5: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groups.aggregate('sum').rename(columns={'Salary': 'Department Expenditure'})

                Department Expenditure  Years of Experience
Department
Administration                  360000                   18
Marketing                       165000                    7
Technical                       315000                   12

In [ ]:
import pandas as pd

#create DataFrame
df = pd.DataFrame({'team': ['A', 'A', 'A', 'A', 'B', 'B', 'B', 'B'],
                   'points': [30, 22, 19, 14, 14, 11, 20, 28]})

#view DataFrame
print(df)

  team  points
0    A      30
1    A      22
2    A      19
3    A      14
4    B      14
5    B      11
6    B      20
7    B      28

In [ ]:
#create new column called sum_points
df['sum_points'] = df.groupby('team')['points'].transform('sum')

#view updated DataFrame
print(df)

  team  points  sum_points
0    A      30          85
1    A      22          85
2    A      19          85
3    A      14          85
4    B      14          73
5    B      11          73
6    B      20          73
7    B      28          73

In [ ]:
#create new column called mean_points
df['mean_points'] = df.groupby('team')['points'].transform('mean')

#view updated DataFrame
print(df)

  team  points  sum_points  mean_points
0    A      30          85        21.25
1    A      22          85        21.25
2    A      19          85        21.25
3    A      14          85        21.25
4    B      14          73        18.25
5    B      11          73        18.25
6    B      20          73        18.25
7    B      28          73        18.25

In [ ]:
#create new column called percent_of_points
df['percent_of_points'] = df.groupby('team')['points'].transform(lambda x: x/x.sum())

#view updated DataFrame
print(df)

  team  points  sum_points  mean_points  percent_of_points
0    A      30          85        21.25           0.352941
1    A      22          85        21.25           0.258824
2    A      19          85        21.25           0.223529
3    A      14          85        21.25           0.164706
4    B      14          73        18.25           0.191781
5    B      11          73        18.25           0.150685
6    B      20          73        18.25           0.273973
7    B      28          73        18.25           0.383562